repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-toml
    - id: trailing-whitespace
      name: Trim Trailing Whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      name: Flake8
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    - id: detect-secrets
      exclude: tests/.*|poetry.lock
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      name: Bandit
      exclude: tests/.*|./.devops/scripts
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
        args: [--ignore=B6, --contrib=CT1, --msg-filename]
        stages: [commit-msg]
