name: 'Setup Python Env'
description: 'Installs python and required dependencies.'

inputs:
  python-version:
    description: 'Python Version'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: cache-python-packages

    - name: Set up the project
      shell: bash
      run: |
        pip install -U pip
        pip install poetry
        poetry config --local
        poetry config virtualenvs.in-project true
        poetry --version
        make setup