name: ⚙️ run tests

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Setup python env
      uses: ./.github/actions/setup-python-env
      with:
        python-version: '3.8'

    - name: Run the test suite
      run: make OUTPUT_DIR=. run-unit-tests-cov

    - name: Upload report coverage.xml
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ github.sha }}
        path: coverage.xml
        if-no-files-found: error
  
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python env
      uses: ./.github/actions/setup-python-env
      with:
        python-version: '3.8'
    
    - name: Start test environment
      run: |
        make prepare-dev
        make start-dev
    
    - name: Check test environment
      run: make check-up-azfn
  
    - name: Run the test suite
      run: make run-integration-tests
    
    - name: Stop test environment
      run: make stop-dev


